import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';
import { parseCookies, validToken, html, esc, DRIVER_CATEGORIES, TTL } from './_shared.mjs';

const DRIVER_STORE = 'parc-chauffeurs';
const REGION = 'eu-central-1';
const store = () => getStore({name: DRIVER_STORE, region: REGION, consistency:'strong'});
const secret = () => process.env.PARC_PASSWORD || '';
function makeToken(id){const exp=Date.now()+TTL;const payload=`${id}.${exp}`;const sig=crypto.createHmac('sha256',secret()).update(payload).digest('hex');return Buffer.from(`${payload}.${sig}`).toString('base64url');}
function adminCookie(){return `PARC_ADMIN=${makeToken('ADMIN')}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${TTL/1000}`}
function isAdmin(req){return validToken(parseCookies(req).PARC_ADMIN,'ADMIN');}
function safePart(s){return String(s||'').replace(/[\\/]/g,'').replace(/^\.+/,'').trim();}
function safeName(s){const n=safePart(s).replace(/[<>:"|?*]/g,'_'); return n || 'document';}
function safeCat(cat){return DRIVER_CATEGORIES[cat] ? cat : null;}
function safeKey(driver,cat,name){if(!driver||!safeCat(cat)||!name)return null;return `docs/${driver}/${cat}/${safeName(name)}`;}
async function drivers(){const {blobs}=await store().list({prefix:'driver/'});const rows=await Promise.all(blobs.map(async b=>store().get(b.key,{type:'json'}).catch(()=>null)));return rows.filter(Boolean).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'fr',{sensitivity:'base'}));}
async function filesForDriver(id){const {blobs}=await store().list({prefix:`docs/${id}/`});return Promise.all(blobs.map(async b=>{const parts=b.key.split('/');const cat=parts[2]||'divers';const name=parts.slice(3).join('/');const m=(await store().getMetadata(b.key).catch(()=>null))?.metadata||{};return {key:b.key,cat,name,label:m.label||name,detail:m.detail||'',expiry:m.expiry||'',contentType:m.contentType||'',uploadedAt:m.uploadedAt||''};}));}
function fmtDate(s){if(!s)return '';const d=new Date(s);return Number.isNaN(d.getTime())?String(s):d.toLocaleDateString('fr-FR');}
function page(body){return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fichiers salariés — THN</title><link rel="stylesheet" href="/style.css"><style>
.fm-toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;position:sticky;top:8px;z-index:10;background:#fff;padding:12px;border:1px solid #d8e6f4;border-radius:14px;box-shadow:0 6px 18px rgba(15,40,70,.07);margin-bottom:16px}.fm-toolbar input{max-width:360px}.fm-clipboard{background:#eef6ff;border:1px solid #cfe0ef;border-radius:10px;padding:8px 10px;color:#0c4f8c;font-weight:700}.fm-tree{display:grid;gap:10px}.fm-driver{border:1px solid #d8e6f4;border-radius:14px;background:#fff;overflow:hidden}.fm-driver>summary{cursor:pointer;list-style:none;padding:13px 16px;display:flex;justify-content:space-between;gap:12px;align-items:center;font-weight:800}.fm-driver>summary::-webkit-details-marker{display:none}.fm-driver>summary:before{content:'📁';margin-right:8px}.fm-driver-main{display:flex;align-items:center;gap:9px;min-width:0}.fm-driver-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.fm-code{font-size:.8rem;color:#0c4f8c;background:#eef6ff;border:1px solid #cfe0ef;border-radius:8px;padding:4px 8px}.fm-cats{padding:0 12px 12px 34px;display:grid;gap:8px}.fm-cat{border:1px solid #e5edf5;border-radius:10px;background:#fbfdff;overflow:hidden}.fm-cat>summary{cursor:pointer;list-style:none;padding:10px 12px;display:flex;align-items:center;justify-content:space-between;gap:10px}.fm-cat>summary::-webkit-details-marker{display:none}.fm-cat>summary:before{content:'📂';margin-right:7px}.fm-cat-title{font-weight:750}.fm-count{font-size:.78rem;color:#6b7f95}.fm-cat-tools{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.fm-cat-tools button{padding:6px 9px;font-size:.82rem}.fm-files{padding:0 10px 10px 12px}.fm-upload{display:grid;grid-template-columns:1fr auto;gap:8px;margin:0 0 10px}.fm-upload input[type=file]{min-width:0}.fm-file{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;padding:9px 8px;border-top:1px solid #e8eef4}.fm-file:first-child{border-top:0}.fm-file-name{display:flex;align-items:center;gap:8px;min-width:0}.fm-file-name a{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.fm-meta{font-size:.78rem;color:#71859a}.fm-actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.fm-actions form{margin:0}.fm-actions input{padding:5px 7px;min-width:170px}.fm-danger{background:#dc2626;color:#fff}.fm-secondary{background:#eef6ff;color:#1264b0}.fm-copy{background:#f2f7fb;color:#0c4f8c}.fm-empty{padding:8px 0;color:#71859a;font-size:.9rem}.fm-rename{display:none}.fm-help{font-size:.86rem;color:#6f8398}.fm-search-hide{display:none!important}@media(max-width:780px){.fm-upload{grid-template-columns:1fr}.fm-file{grid-template-columns:1fr}.fm-actions{justify-content:flex-start}}
</style></head><body><main>${body}<div style="text-align:center;padding:18px;color:#6b7f95">THN — Administration &nbsp; | &nbsp; Version <strong>V112</strong></div></main></body></html>`;}
function renderFile(f,driver,cat){const catLabel=DRIVER_CATEGORIES[cat]?.label||cat;return `<div class="fm-file searchable-file" data-file-search="${esc((f.name+' '+f.detail+' '+catLabel).toLowerCase())}"><div><div class="fm-file-name"><span>📄</span><a target="_blank" rel="noopener" href="/.netlify/functions/driver-document/${encodeURIComponent(driver.id)}/${encodeURIComponent(cat)}/${encodeURIComponent(f.name)}">${esc(f.name)}</a></div><div class="fm-meta">${f.detail?esc(f.detail)+' · ':''}${f.expiry?'Échéance : '+esc(fmtDate(f.expiry))+' · ':''}${f.uploadedAt?'Ajouté : '+esc(fmtDate(f.uploadedAt)):''}</div></div><div class="fm-actions"><button type="button" class="fm-copy" data-copy-key="${esc(f.key)}" data-copy-name="${esc(f.name)}">Copier</button><button type="button" class="fm-secondary rename-toggle">Renommer</button><form method="post" action="/.netlify/functions/driver-files" class="fm-rename"><input type="hidden" name="action" value="rename"><input type="hidden" name="driver" value="${esc(driver.id)}"><input type="hidden" name="cat" value="${esc(cat)}"><input type="hidden" name="oldName" value="${esc(f.name)}"><input name="newName" value="${esc(f.name)}" aria-label="Nouveau nom"><button class="fm-secondary">OK</button></form><form method="post" action="/.netlify/functions/driver-files" onsubmit="return confirm('Supprimer définitivement ce fichier ?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="key" value="${esc(f.key)}"><input type="hidden" name="driver" value="${esc(driver.id)}"><button class="fm-danger">Supprimer</button></form></div></div>`;}
function renderCategory(driver,cat,files,open=false){const label=DRIVER_CATEGORIES[cat]?.label||cat;const icon=DRIVER_CATEGORIES[cat]?.icon||'📂';const selectedFiles=files.filter(f=>f.cat===cat).sort((a,b)=>a.name.localeCompare(b.name,'fr',{sensitivity:'base'}));return `<details class="fm-cat" ${open?'open':''} data-driver="${esc(driver.id)}" data-cat="${esc(cat)}"><summary><span class="fm-cat-title">${icon} ${esc(label)}</span><span class="fm-cat-tools"><span class="fm-count">${selectedFiles.length} fichier${selectedFiles.length>1?'s':''}</span><button type="button" class="fm-secondary paste-here" data-driver="${esc(driver.id)}" data-cat="${esc(cat)}">Coller</button></span></summary><div class="fm-files"><form method="post" action="/.netlify/functions/driver-files" enctype="multipart/form-data" class="fm-upload"><input type="hidden" name="action" value="upload"><input type="hidden" name="driver" value="${esc(driver.id)}"><input type="hidden" name="cat" value="${esc(cat)}"><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.txt" required><button>Ajouter</button></form>${selectedFiles.length?selectedFiles.map(f=>renderFile(f,driver,cat)).join(''):'<div class="fm-empty">Aucun document dans ce dossier.</div>'}</div></details>`;}
function render(driver,files,selectedCat=''){const cats=Object.keys(DRIVER_CATEGORIES);return `<details class="fm-driver" data-driver-name="${esc(driver.name.toLowerCase())}"><summary><span class="fm-driver-main"><span class="fm-driver-name">${esc(driver.name)}</span></span><span class="fm-code">🔑 ${esc(driver.accessCode||driver.code||'—')}</span></summary><div class="fm-cats">${cats.map(cat=>renderCategory(driver,cat,files,selectedCat===cat)).join('')}</div></details>`;}
async function rebuildDriverDocument(key,newKey,meta){const data=await store().get(key,{type:'arrayBuffer'});if(!data)throw new Error('Fichier source introuvable');await store().set(newKey,data,{metadata:meta||{}});await store().delete(key);}
async function uniqueTargetKey(driver,cat,desired,sourceKey=''){const base=safeName(desired);let key=`docs/${driver}/${cat}/${base}`;if(key===sourceKey)return key;let exists=await store().get(key,{type:'arrayBuffer'}).catch(()=>null);if(!exists)return key;const dot=base.lastIndexOf('.');const stem=dot>0?base.slice(0,dot):base;const ext=dot>0?base.slice(dot):'';for(let i=2;i<9999;i++){const candidate=`docs/${driver}/${cat}/${stem} (copie ${i})${ext}`;const e=await store().get(candidate,{type:'arrayBuffer'}).catch(()=>null);if(!e)return candidate;}throw new Error('Impossible de trouver un nom de fichier disponible');}

export default async req=>{
  try{
    if(!isAdmin(req)) return html(page(`<div class="box"><p><a href="/admin.html">← Accès administration</a></p><h2>Session administrateur</h2><p class="muted">Votre session a expiré.</p></div>`),401);
    const url=new URL(req.url);
    if(req.method==='POST'){
      const fd=await req.formData(); const action=String(fd.get('action')||'');
      if(action==='upload'){
        const driver=safePart(fd.get('driver')); const cat=safeCat(fd.get('cat')); const file=fd.get('file');
        if(!driver||!cat||!(file instanceof File)||!file.size)return html(page(`<div class="box"><p class="bad">Fichier invalide.</p><p><a href="/driver-files?driver=${encodeURIComponent(driver)}&cat=${encodeURIComponent(cat)}">Retour</a></p></div>`),400);
        if(file.size>4.5*1024*1024)return html(page(`<div class="box"><p class="bad">Fichier trop volumineux pour un chargement direct. Utilise l’import complet pour les gros fichiers (plus de 4,5 Mo).</p><p><a href="/driver-files?driver=${encodeURIComponent(driver)}&cat=${encodeURIComponent(cat)}">Retour</a></p></div>`),413);
        const name=safeName(file.name); const key=`docs/${driver}/${cat}/${name}`;
        const meta={label:name,detail:'',expiry:'',contentType:file.type||'application/octet-stream',uploadedAt:new Date().toISOString()};
        await store().set(key,await file.arrayBuffer(),{metadata:meta});
        return new Response(null,{status:303,headers:{Location:`/driver-files?driver=${encodeURIComponent(driver)}&cat=${encodeURIComponent(cat)}`, 'Set-Cookie':adminCookie()}});
      }
      if(action==='delete'){
        const key=String(fd.get('key')||''); const driver=safePart(fd.get('driver')); if(!key.startsWith(`docs/${driver}/`))throw new Error('Fichier invalide'); await store().delete(key); return new Response(null,{status:303,headers:{Location:`/driver-files?driver=${encodeURIComponent(driver)}`, 'Set-Cookie':adminCookie()}});
      }
      if(action==='rename'){
        const driver=safePart(fd.get('driver')); const cat=safeCat(fd.get('cat')); const oldName=safeName(fd.get('oldName')); const newName=safeName(fd.get('newName')); if(!driver||!cat||!newName)throw new Error('Nom de fichier invalide');
        const oldKey=`docs/${driver}/${cat}/${oldName}`; const meta=(await store().getMetadata(oldKey).catch(()=>null))?.metadata||{}; const newKey=await uniqueTargetKey(driver,cat,newName,oldKey); await rebuildDriverDocument(oldKey,newKey,meta); return new Response(null,{status:303,headers:{Location:`/driver-files?driver=${encodeURIComponent(driver)}&cat=${encodeURIComponent(cat)}`,'Set-Cookie':adminCookie()}});
      }
      if(action==='paste'){
        const sourceKey=String(fd.get('sourceKey')||''); const driver=safePart(fd.get('driver')); const cat=safeCat(fd.get('cat')); if(!sourceKey.startsWith('docs/'))throw new Error('Source invalide');
        const sp=sourceKey.split('/'); const sourceName=safeName(sp.slice(3).join('/')); if(!sourceName)throw new Error('Source invalide'); const data=await store().get(sourceKey,{type:'arrayBuffer'}); if(!data)throw new Error('Fichier source introuvable'); const meta=(await store().getMetadata(sourceKey).catch(()=>null))?.metadata||{}; const newKey=await uniqueTargetKey(driver,cat,sourceName,''); await store().set(newKey,data,{metadata:{...meta,uploadedAt:new Date().toISOString(),copiedFrom:sourceKey}}); return new Response(null,{status:303,headers:{Location:`/driver-files?driver=${encodeURIComponent(driver)}&cat=${encodeURIComponent(cat)}`,'Set-Cookie':adminCookie()}});
      }
    }
    const ds=await drivers(); const selectedDriver=safePart(url.searchParams.get('driver')); const selectedCat=safeCat(url.searchParams.get('cat')||''); const all=await Promise.all(ds.map(async d=>({d,files:await filesForDriver(d.id)})));
    const tree=all.map(({d,files})=>render(d,files,selectedDriver===d.id?selectedCat:'')).join('');
    const body=`<div class="box"><p><a href="/netlify/functions/admin">← Administration</a></p><div class="fm-toolbar"><input id="fm-search" type="search" placeholder="🔎 Rechercher un salarié ou un document..."><span id="fm-clipboard" class="fm-clipboard">Presse <strong>Copier</strong> sur un fichier pour le mettre en mémoire.</span></div><div class="box"><h1>🗂️ Gestionnaire de fichiers salariés</h1><p class="fm-help">Organisation par salarié et par dossier. Tu peux ajouter, supprimer, renommer, copier et coller les documents comme dans un gestionnaire de fichiers Windows.</p></div><div class="fm-tree">${tree||'<div class="box"><p class="muted">Aucun salarié enregistré.</p></div>'}</div></div><script>
const cbKey='thnDriverFileClipboard';const clipEl=document.getElementById('fm-clipboard');function getClip(){try{return JSON.parse(localStorage.getItem(cbKey)||'null')}catch{return null}}function setClip(c){localStorage.setItem(cbKey,JSON.stringify(c));renderClip()}function renderClip(){const c=getClip();clipEl.innerHTML=c?('📋 Fichier copié : <strong>'+String(c.name||'').replace(/</g,'&lt;')+'</strong> — clique sur <strong>Coller</strong> dans le dossier cible.'):'Presse <strong>Copier</strong> sur un fichier pour le mettre en mémoire.';}renderClip();
document.querySelectorAll('.rename-toggle').forEach(b=>b.addEventListener('click',()=>{const f=b.parentElement.querySelector('.fm-rename');if(f){f.style.display=f.style.display==='flex'?'none':'flex';f.style.gap='6px';}}));
document.querySelectorAll('[data-copy-key]').forEach(b=>b.addEventListener('click',()=>{setClip({key:b.dataset.copyKey,name:b.dataset.copyName});}));
document.querySelectorAll('.paste-here').forEach(b=>b.addEventListener('click',async()=>{const c=getClip();if(!c){alert('Aucun fichier copié.');return;}const fd=new FormData();fd.append('action','paste');fd.append('sourceKey',c.key);fd.append('driver',b.dataset.driver);fd.append('cat',b.dataset.cat);b.disabled=true;try{const r=await fetch('/.netlify/functions/driver-files',{method:'POST',body:fd,credentials:'same-origin'});if(!r.ok)throw new Error(await r.text());localStorage.removeItem(cbKey);location.reload();}catch(e){alert('Impossible de coller le fichier : '+(e.message||e));b.disabled=false;}}));
const search=document.getElementById('fm-search');search?.addEventListener('input',()=>{const q=search.value.toLowerCase().trim();document.querySelectorAll('.fm-driver').forEach(d=>{const matchName=(d.dataset.driverName||'').includes(q);let hasFile=false;d.querySelectorAll('.searchable-file').forEach(f=>{const hit=!q||(f.dataset.fileSearch||'').includes(q)||matchName;f.classList.toggle('fm-search-hide',!hit);if(hit)hasFile=true;});d.style.display=!q||matchName||hasFile?'':'none';if(q&&(matchName||hasFile))d.open=true;});});
</script>`;
    return html(page(body),200,{'Set-Cookie':adminCookie(),'Cache-Control':'no-store'});
  }catch(e){return html(page(`<div class="box"><h2>Erreur</h2><p class="bad">${esc(e?.message||String(e))}</p><p><a href="/netlify/functions/admin">← Administration</a></p></div>`),500)}
};
