[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/machine/:id"
  to = "/.netlify/functions/machine?id=:id"
  status = 200

[[redirects]]
  from = "/document/:id/:name"
  to = "/.netlify/functions/document?id=:id&name=:name"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/admin"
  status = 200
